fetch_all_adjust_reports:
  cron: "2 * * * * Asia/Hong_Kong"
  class: "FetchAllAdjustReportJob"
  queue: "queue-ads-data"
  args:
  description: "每小时拉取所有的Adjust报告数据"

fetch_all_facebook_reports:
  cron: "2 * * * * Asia/Hong_Kong"
  class: "FetchAllFacebookReportJob"
  queue: "queue-ads-data"
  args:

check_all_automation_rules:
  cron: "15 * * * * Asia/Hong_Kong"
  class: "CheckAllAutomationRuleJob"
  queue: "check_automation_rule"
  args:
